### ISSUE TITLE
[Bug] Cannot look at character with missing artifact(s)

### ISSUE THREAD

**Issue by soleilvermeil** [eikofee/eikonomiya-front#14]
**Describe the bug**
When I access a character who don't have all 5 artifacts equiped, I get the following error:
```
TypeError: Cannot read properties of undefined (reading 'mainStat')
    at eN (/app/.next/server/app/[uid]/[character]/page.js:1:63911)
    at nT (/app/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:46138)
    at nO (/app/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:62795)
    at nI (/app/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:65445)
    at nj (/app/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:64852)
    at nO (/app/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:63041)
    at nI (/app/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:65445)
    at nT (/app/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:57207)
    at nO (/app/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:62795)
    at nR (/app/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:45694)
```

**Comment by eikofee** [comment]
fixed in bb99b8a2076c71be655c2ae2da5ad2c31bc29321.
